name: Release

on:
  push:
    branches:
      - master

jobs:
  # bump-version:
  #   name: Bump version and create new tag
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4.1.4
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: cat package.json
  #       run: cat ./package.json

  #     - name: Automated version bump
  #       id: version-bump
  #       uses: phips28/gh-action-bump-version@master
  #       with:
  #         tag-prefix: "v"
  #         skip-tag: "true" # Add tag later in the release job
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: cat package.json
  #       run: cat ./package.json
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs:
    #   - bump-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: ZIP build
        run: zip -r build.zip build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: npx semantic-release --branches master
